name-template: 'meeting-operator-v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'api-change'
    files:
      - '/apis/**/*'
  - label: 'etherpad'
    files:
      - '/internal/etherpad/*'
  - label: 'jitsi'
    files:
      - '/internal/jitsi/**/*'
  - label: 'autoscaler'
    files:
      - '/internal/jitsiautoscaler/*'
  - label: 'utils'
    files:
      - '/internal/utils/*'
  - label: 'whiteboard'
    files:
      - '/internal/whiteboard/*'
  - label: 'documentation'
    files:
      - '**/*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'deploy'
    files:
      - 'deploy/**/*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
template: |
  ## Changes
  $CHANGES
