
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-etherpad
  failurePolicy: Fail
  name: etherpad.meeting.ko
  rules:
  - apiGroups:
    - etherpad.meeting.ko
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - etherpads
  sideEffects: None
