# permissions for end users to edit whiteboadrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whiteboadrd-editor-role
rules:
- apiGroups:
  - meeting.ko
  resources:
  - whiteboadrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - whiteboadrds/status
  verbs:
  - get
