# permissions for end users to view whiteboadrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whiteboadrd-viewer-role
rules:
- apiGroups:
  - meeting.ko
  resources:
  - whiteboadrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - whiteboadrds/status
  verbs:
  - get
