# permissions for end users to view etherpads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etherpad-viewer-role
rules:
- apiGroups:
  - meeting.ko
  resources:
  - etherpads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - etherpads/status
  verbs:
  - get
