apiVersion: meeting.ko/v1alpha1
kind: Jitsi
metadata:
  name: jitsi-sample
spec:
  web:
    replicas: 1
    image: jitsi/web:stable-5390-3
    image_pull_secrets:
    - name: docker
    service_annotations: {}
    service_type: "LoadBalancer"
    services:
      - port_name: "http"
        protocol: "TCP"
        port: 80
    environments:
    - name: ENABLE_LETSENCRYPT
      value: "0"
    - name: XMPP_SERVER
      value: prosody
    - name: JICOFO_AUTH_USER
      value: focus
    - name: XMPP_DOMAIN
      value: prosody
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.jitsi
    - name: XMPP_BOSH_URL_BASE
      value: http://prosody:5280
    - name: TZ
      value: UTC
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "false"
    - name: DISABLE_HTTPS
      value: "1"
    - name: PUBLIC_URL
      value: https://<<your public url here>>
    - name: ETHERPAD_URL_BASE
      value: http://etherpad:9001/p/
    - name: ETHERPAD_PUBLIC_URL
      value: https://<<your ehterpad public url here>>/p/

  jicofo:
    replicas: 1
    image: jitsi/jicofo:stable-5390-3
    service_type: "ClusterIP"
    services:
      - port_name: "jicofo"
        protocol: "TCP"
        port: 5280
    environments:
    - name: XMPP_SERVER
      value: prosody
    - name: XMPP_DOMAIN
      value: prosody
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.jitsi
    - name: TZ
      value: UTC
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: PUBLIC_URL
      value: https://<<your public url here>>
    - name: JICOFO_COMPONENT_SECRET
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_COMPONENT_SECRET
    - name: JICOFO_AUTH_USER
      value: focus
    - name: JICOFO_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_AUTH_PASSWORD

  prosody:
    replicas: 1
    service_type: "ClusterIP"
    services:
      - port_name: "http"
        protocol: "TCP"
        port: 5282
      - port_name: "xmpp"
        protocol: "TCP"
        port: 5222
      - port_name: "external"
        protocol: "TCP"
        port: 5347
    image: jitsi/prosody:stable-5390-3
    environments:
    - name: XMPP_DOMAIN
      value: prosody
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.jitsi
    - name: JICOFO_COMPONENT_SECRET
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_COMPONENT_SECRET
    - name: JVB_AUTH_USER
      value: jvb
    - name: JVB_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JVB_AUTH_PASSWORD
    - name: JICOFO_AUTH_USER
      value: focus
    - name: JICOFO_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_AUTH_PASSWORD
    - name: JIBRI_XMPP_USER
      value: jibri
    - name: JIBRI_XMPP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JIBRI_XMPP_PASSWORD
    - name: JIBRI_RECORDER_USER
      value: jibri
    - name: JIBRI_RECORDER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JIBRI_RECORDER_PASSWORD
    - name: TZ
      value: UTC
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "false"
    - name: DISABLE_HTTPS
      value: "1"
    - name: PUBLIC_URL
      value: https://<<your public url here>>

  jibri:
    replicas: 1
    storage:
      empty_dir: {}
#        sizeLimit:
#          "1Gi"
#      pvc: {}
##        apiVersion: v1
##        kind: PersistentVolumeClaim
##        spec:
##          accessModes: ["ReadWriteOnce"]
##          resources:
##            requests:
##              storage: "1Gi"
#    service_type: "ClusterIP"
    services:
      - port_name: "http"
        protocol: "TCP"
        port: 5282
    environments:
      - name: JIBRI_RECORDING_DIR
        value: /config/recordings
      - name: DISPLAY
        value: ":0"
      - name: XMPP_SERVER
        value: prosody
      - name: XMPP_DOMAIN
        value: prosody
      - name: XMPP_AUTH_DOMAIN
        value: auth.jitsi.jitsi
      - name: XMPP_INTERNAL_MUC_DOMAIN
        value: internal-muc.jitsi.jitsi
      - name: XMPP_RECORDER_DOMAIN
        value: recorder.meet.jitsi
      - name: JIBRI_BREWERY_MUC
        value: jibribrewery
      - name: JIBRI_RECORDER_USER
        value: recorder
      - name: JIBRI_RECORDER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jitsi-config
            key: JIBRI_RECORDER_PASSWORD
      - name: JIBRI_XMPP_USER
        value: jibri
      - name: JIBRI_XMPP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jitsi-config
            key: JIBRI_XMPP_PASSWORD
      - name: JIBRI_STRIP_DOMAIN_JID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name

  jvb:
    replicas: 1
    image: jitsi/jvb:stable-5390-3
    service_annotations: {}
    service_type: "LoadBalancer"
    service:
      port_name: "jvb"
      protocol: "UDP"
    environments:
    - name: XMPP_SERVER
      value: prosody
    - name: XMPP_DOMAIN
      value: prosody
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.jitsi
#    - name: JVB_STUN_SERVERS
#      value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
    - name: JVB_ENABLE_APIS
      value: colibri,rest
    - name: JICOFO_AUTH_USER
      value: focus
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "false"
    - name: JVB_AUTH_USER
      value: jvb
    - name: JVB_PORT
      value: "30300"
#    - name: JVB_TCP_PORT
#      value: "4443"
#    - name: JVB_TCP_MAPPED_PORT
#      value: "4443"
    - name: JVB_BREWERY_MUC
      value: jvbbrewery
    - name: TZ
      value: UTC
    - name: JICOFO_ENABLE_HEALTH_CHECKS
      value: "false"
    - name: PUBLIC_URL
      value: https://<<your public url here>>
    - name: DISABLE_AWS_HARVESTER
      value: "true"
    - name: JVB_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JVB_AUTH_PASSWORD
    - name: JICOFO_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_AUTH_PASSWORD
#    - name: DOCKER_HOST_ADDRESS
#      value: <your public ip here>
      # valueFrom:
      #   fieldRef:
      #     fieldPath: status.hostIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
