apiVersion: jitsi.meeting.ko/v1beta1
kind: Web
metadata:
  name: web-sample
spec:
  deployment_spec:
    replicas: 1
    image: jitsi/web:stable-5390-3
    security_context:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
    image_pull_secrets:
      - name: docker
    resources:
      requests:
        cpu: "0.1"
        memory: "128Mi"
    environments:
    - name: ENABLE_LETSENCRYPT
      value: "0"
    - name: XMPP_SERVER
      value: prosody
    - name: JICOFO_AUTH_USER
      value: focus
    - name: XMPP_DOMAIN
      value: prosody
    - name: XMPP_AUTH_DOMAIN
      value: auth.jitsi.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.jitsi.jitsi
    - name: XMPP_MUC_DOMAIN
      value: muc.jitsi.jitsi
    - name: XMPP_BOSH_URL_BASE
      value: http://prosody:5280
    - name: TZ
      value: UTC
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
    - name: DISABLE_HTTPS
      value: "1"
    - name: PUBLIC_URL
      value: https://<<your public url here>>
    # - name: ETHERPAD_URL_BASE
    #   value: http://etherpad:9001/p/
    # - name: ETHERPAD_PUBLIC_URL
    #   value: https://<<your ehterpad public url here>>/p/
  service_type: "ClusterIP"
  service_annotations:
    sample: "yes"
  ports:
    - name: https
      protocol: "TCP"
      port: 443
