apiVersion: v1
kind: ConfigMap
metadata:
  name: jvb-telegraf-config
data:
  telegraf.conf: |
    [[inputs.http]]
      name_override = "jitsi_stats"
      urls = ["http://localhost:8080/colibri/stats"]
      data_format = "json"
    [[outputs.influxdb_v2]]
      urls = ["http://influx-influxdb2:80"]
      token = "your token"
      bucket = "jitsi"
      organization = "influxdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jicofo-telegraf-config
data:
  telegraf.conf: |
    [[inputs.http]]
      name_override = "jitsi_stats"
      urls = ["http://localhost:8888/stats"]
      data_format = "json"
    [[outputs.influxdb_v2]]
      urls = ["http://influx-influxdb2:80"]
      token = "your token"
      bucket = "jitsi"
      organization = "influxdata"