# permissions for end users to edit etherpads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etherpad-editor-role
rules:
- apiGroups:
  - meeting.ko
  resources:
  - etherpads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - etherpads/status
  verbs:
  - get
