---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meeting-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jibris
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jibris/finalizers
  verbs:
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jibris/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jicofoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jicofoes/finalizers
  verbs:
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jicofoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jigasis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jigasis/finalizers
  verbs:
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jigasis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jvbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jvbs/finalizers
  verbs:
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - jvbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - prosodies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - prosodies/finalizers
  verbs:
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - prosodies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - webs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - webs/finalizers
  verbs:
  - update
- apiGroups:
  - jitsi.meeting.ko
  resources:
  - webs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meeting.ko
  resources:
  - autoscalers
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - etherpads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - etherpads/finalizers
  verbs:
  - update
- apiGroups:
  - meeting.ko
  resources:
  - etherpads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meeting.ko
  resources:
  - whiteboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meeting.ko
  resources:
  - whiteboards/finalizers
  verbs:
  - update
- apiGroups:
  - meeting.ko
  resources:
  - whiteboards/status
  verbs:
  - get
  - patch
  - update
