name: Release - Helm

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.4.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with:
          charts_dir: deploy/helm
        env:
          CR_TOKEN: '${{ secrets.CUSTOM_GITHUB_TOKEN }}'
          CR_RELEASE_NAME_TEMPLATE: 'v{{ .Version }}'
          CR_SKIP_EXISTING: true

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET }}
      - name: Deploy to Artifactory 
        run: | 
          helm package deploy/helm/meeting-operator/
          jfrog rt u "*.tgz" jitsi-helm
