name: PR - Go

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
      - 'deploy/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'deploy/**'
      - 'docs/**'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build

      - name: Test
        run: go test
